### ISSUE TITLE
运行install bat报错

### ISSUE THREAD

**Issue by Sakura-1997** [Fauture/GbitsShellExtThumbnailHandler#3]
模块”
D:\test\GbitsShellExtThumbnailHandler-masterGbitsShellExtThumbnailHandler-masterGbitsShellExtThumbnailHandler.dl"加载失败
请确保该二进制存储在指定的路径中，或者调试它以检查该二进制或相关的DLL文件是否有问题。
找不到指定的模块，

**Comment by Fauture** [comment]
你文件名称怎么这么长

**Comment by Fauture** [comment]
你下载的源码?编译出dll没

**Comment by Sakura-1997** [comment]
小白&nbsp; 不会编译&nbsp; ...&nbsp;


蛋卷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fauture/GbitsShellExtThumbnailHandler] 运行install bat报错 (Issue #3)














 
你下载的源码?编译出dll没

**Comment by Fauture** [comment]
不会编译就下载这个成品
https://github.com/Fauture/GbitsShellExtThumbnailHandler/releases

**Comment by Fauture** [comment]
不会编译就下载这个成品
https://github.com/Fauture/GbitsShellExtThumbnailHandler/releases

**Comment by Sakura-1997** [comment]
好嘞&nbsp; &nbsp;感谢
&nbsp;


蛋卷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 下午2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fauture/GbitsShellExtThumbnailHandler] 运行install bat报错 (Issue #3)














 
不会编译就下载这个成品
 https://github.com/Fauture/GbitsShellExtThumbnailHandler/releases
